version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: 'laravelapp'
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #nginx configuration
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #mysql configuration
  db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '7000:80'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
