export const FOLLOWER_LOAD = 'FOLLOWER_LOAD';
export const FOLLOWER_CREATE = 'FOLLOWER_CREATE';
export const FOLLOWER_READ = 'FOLLOWER_READ';
export const FOLLOWER_UPDATE = 'FOLLOWER_UPDATE';
export const FOLLOWER_DELETE = 'FOLLOWER_DELETE';
export const FOLLOWER_ERROR = 'FOLLOWER_ERROR';
